# Generated by Django 5.2.8 on 2026-01-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('coding_experience', models.TextField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, null=True)),
                ('date_and_time', models.DateTimeField(blank=True, null=True)),
                ('room', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trial',
                'managed': False,
            },
        ),
    ]
